### ISSUE TITLE
3d armor can erase items

### ISSUE THREAD

**Issue by fluxionary** [BlockySurvival/issue-tracker#51]
If you drag 3d armor onto an item in your inventory that is not armor, it will erase it.

**Comment by bhree** [comment]
how about adding
`minetest.item_drop(stack, player, pos)` after `inv:remove_item("armor", stack)` at line 143 init.lua

**Comment by fluxionary** [comment]
Totally reasonable suggestion, bhree. 
If possible, maybe put in a PR w/ 3d_armor? Though they've never responded to my issue...
Also, I've noticed this behaviour from a lot of other mods since someone reported this issue to me. Mods don't seem to check the result of inventory actions very thoroughly...

**Comment by bhree** [comment]
I'll try to put PR although i don't have any idea about mentioned hacked client and possibility of exploit. Hopefully can raise better suggestion.

**Comment by thomasrudin** [comment]
@fluxionary @bhree judging from the activity of @stujones11 and the missing responses i think he is no longer active :disappointed: 

Can we fork the `3d_armor` mod somewhere and fix the existing bugs together :smile: ?
We do have some issues with it too:
* https://github.com/pandorabox-io/pandorabox.io/issues/365
* https://github.com/pandorabox-io/pandorabox.io/issues/364

**Comment by fluxionary** [comment]
@thomasrudin not sure if you have any pull in this, but it feels like it's a widely used enough mod that it might deserve to be part of the github.com/minetest-mods. I don't feel like I should take the mod over myself, as my health has been declining over the last year and I've been doing less coding myself in the last two months.

**Comment by thomasrudin** [comment]
> not sure if you have any pull in this

not really, no :/ see: https://github.com/stujones11/minetest-3d_armor/pull/168#issuecomment-559237030

> I don't feel like I should take the mod over myself, as my health has been declining over the last year

Sorry to hear that... I've seen this pattern a few times already.
I'm assuming this is because of your increasing involvement in the minetest community (i do hope so, because thats actually fixable :smile:).

Why don't you take a break from all of this? I'm sure nobody will get mad if you disappear for a while (and come back with a bag full of ideas...) or just step down a little..

You did quite good work from what i have seen (on Blocky, minetest and several of its mods) but don't neglect your health, its only a game after all...

**Comment by fluxionary** [comment]
Thanks for the concern thomasrudin, but coding on this game is about all the work I can manage at this point, and I enjoy it and I think it helps me a lot. I promise I'm not hurting myself doing this, particularly not for the sake of the game :)

**Comment by Lanhild** [comment]
Solved, I guess? I tested and when you place armor onto an occupied slot, the previous item that was in the slot is dropped.
