### ISSUE TITLE
unified_inventory: make "most reasonable" crafting recipes show up first

### ISSUE THREAD

**Issue by fluxionary** [BlockySurvival/issue-tracker#92]
Specific examples:
* Moreblocks recipes should not show up first (unless there are no other recipes). I'd prefer if they didn't show up at all, even. 
* Torch recipe should show stick + coal, not biomatter
* Recipes for items shouldn't show how it can be crafted from a block first
* Recipes for ingots should show smelting lumps, not weird stuff
* Recipes for tools shouldn't show the equipment reformer first
* Recipe for sticks should show wood first
* There are many more examples (bricks, glass, ...)

**Comment by fluxionary** [comment]
I feel like we can come up with a number of heuristics for ordering them, but I also feel like a lot of the time it's going to require manual intervention somehow. 

The ordering of the crafting recipes has been an annoyance for a long time, but the specific thing that came up this time, was that a new player asked me how to craft a "Biomatter Block Microblock". It took me a moment to realize why they wanted to know this: they wanted to make torches. The default torch recipe indicated that torches were made from sticks and biomatter. Biomatter was made from biomatter blocks. And biomatter blocks were made from the microblocks, which were apparently uncraftable (because the circular saw does not register its recipes). No step in this chain gave the most reasonable recipe.

**Comment by krypticbit** [comment]
No algorithm is perfect, but things could be a lot better even if recipes were arranged so that ones requiring part of a block (like a microblock, or the hundred other variations existing through the saw) to be last.

**Comment by ExeVirus** [comment]
Reality check: does anyone actually use those 18 or so recipes to put together blocks?
     Except the half-node slope and slab? 

Couldn't we just remove those and help de-clutter?

**Comment by krypticbit** [comment]
It's quite possible that we could ...

**Comment by krypticbit** [comment]
I'd suggest combining these two ideas, in other words having an algorithm that does the following:

1. For each recipe, take the sum of the number of times each item was referenced, but don't count the recipes for putting together blocks when taking the sum.
2. Based on these numbers, order the recipes from highest to lowest

Then for something like a torch, a coal lump and a stick are both referenced many times so that would probably be the first recipe shown.  At any rate, it certainly wouldn't be something with microblocks as very few recipes actually use them.
